### ISSUE TITLE
0211[WIKI]翻译时, 在标题增加翻译人及进展

### ISSUE THREAD

**Issue by OMlalala** [DebugUself/leo-editor-cn#10]
### 背景
0208, 大妈在 slack 中提醒, 为了完成工程进程的显性化, 及时看到他人修订结果, 需要在对应标题中签入 ``翻译人以及进展``

如, ``zoomquiet`` 想翻译 ``Cheat Sheet``, 目前刚开始翻译, 可以按如下格式标注: ``(ZQ:0%)Cheat Sheet``

![](http://omjtq6wcu.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-02-08%2000.07.54.png)

### 待做
0211 前, 将上面内容, 增补 wiki 对应内容.

**Comment by ZoomQuiet** [comment]
@OMlalala 是也乎,(￣▽￣)
超时了,,,没见嗯哼?

**Comment by OMlalala** [comment]
交付 --> [认领翻译](https://github.com/DebugUself/leo-editor-cn/wiki/How2Register)
