### ISSUE TITLE
Installing Leo

### ISSUE THREAD

**Issue by livingworld** [DebugUself/leo-editor-cn#14]
- 原文链接:[Installing Leo — Leo 5.7 documentation](http://leoeditor.com/installing.html)
- PR 地址: #25

**Comment by OMlalala** [comment]
根据 [0222 讨论结果](https://github.com/DebugUself/leo-editor-cn/issues/1#issuecomment-367904643), 怼友基于各自的 .leo 文件, 分片包干儿持续翻译
翻译进度请在跟目录的 OBP.leo 持续更新哦
Duplicate of #1
