### ISSUE TITLE
Downloading Leo

### ISSUE THREAD

**Issue by livingworld** [DebugUself/leo-editor-cn#7]
- 原文链接:[Downloading Leo — Leo 5.7 documentation](http://leoeditor.com/download.html)
- PR 地址:

**Comment by livingworld** [comment]
@OMlalala 我是还没有权限么？无法添加label和提交分支。

**Comment by ZoomQuiet** [comment]
@livingworld 目测是 PR 形式的参与...
所以, 无法直接嗯哼....

**Comment by OMlalala** [comment]
@livingworld 
我新建了一个 team: [DU4leo](https://github.com/orgs/DebugUself/teams/du4leo/members), 针对想参加释狮大会的怼友. 
目的: 加入 team, 可获得此仓库的管理员权限.  欢迎~
其他非怼圈的朋友, 通过 PR 形式参与, 我本周增补相关 wiki

**Comment by ZoomQuiet** [comment]
@OMlalala 统一引导到维基
具体策略讨论在: [[init.]如何加入协同翻译?](https://github.com/DebugUself/leo-editor-cn/issues/1)

Duplicate of #1
