### ISSUE TITLE
Pussy riot slide show not null.  

### ISSUE THREAD

**Issue by lorilorr1** [DebugUself/leo-editor-cn#8]
Or isreal

**Comment by OMlalala** [comment]
Hi, welcome
Thanks for opening a issue, but I just don't understand what's your idea.
Could you pelase change another description, thank you~

**Comment by OMlalala** [comment]
@lorilorr1 
Hi, I will close this issue.
Welcome to reopen this issue, and change another description to express your idea.
Thanks to your concern.
